Removed apparently unused attribute over errors.
Due to Mono upgrading to CSC with the 5.0 release, attempting to make
the project was now resulting in the error: "CSC: error CS8105: Attribute
'System.Reflection.AssemblyKeyNameAttribute' is ignored when public
signing is specified."